name: Test
on: [push, pull_request]

jobs:
  test:
    name: Run tests
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          submodules: true
      - name: Build
        run: |
          cmake . -B build -DENABLE_TESTS=ON
          make -C build
      - name: Test
        run: make -C build test

